### ISSUE TITLE
关于使用dialog的时候发生的错误

### ISSUE THREAD

**Issue by a1b22003001** [genius158/InflaterAuto#3]
在使用dialog的时候，在dialog.setContentView这里会报错，我不确定是我的inflate方法用的不对还是setContentView用的不对，所以希望您能出一个dialog的使用demo

**Comment by genius158** [comment]
@a1b22003001 好的 后面会 看一下
这两天 电脑 没在自己这里，暂时无法

**Comment by genius158** [comment]
@a1b22003001 已经调整过了，2.0.16 版本

**Comment by a1b22003001** [comment]
thanks
