### ISSUE TITLE
关于padding和margin的值是dp的问题

### ISSUE THREAD

**Issue by a1b22003001** [genius158/InflaterAuto#4]
我在使用Snackbar的过程中发现snackbar的padding没了，然后看您的源码发现是只对px的值做了计算，而dp的值就直接continue了，这样在使用snackbar或者一些第三方库的时候显示会很不友好

**Comment by genius158** [comment]
@a1b22003001 padding值没有了？
在autoView之前view生成的时候就已经设置过一遍值了，所以只需调整px的。

**Comment by a1b22003001** [comment]
我发现当使用dialog的时候，如果在activity中加入super.attachBaseContext(InflaterAuto.wrap(base)),内间距会消失，但是去掉这距代码后又会出现

**Comment by genius158** [comment]
demo里有Dialog例子，你是要保留系统默认边距？

**Comment by a1b22003001** [comment]
我现在有2个地方发现问题，1.在使用dialog的时候，view布局的最顶层view的padding的值单位如果是dp，那就会无效，但是px就会有效.  2.在使用snackBar的时候，边距会消失。 现在是发现这2种情况

**Comment by genius158** [comment]
好的，我看一下

**Comment by genius158** [comment]
@a1b22003001   是的padding那里确实有问题
可以试试2.0.17
snackbar应该也是一个问题

还有，谢谢你提的issue,希望一起完善这个库😁

**Comment by a1b22003001** [comment]
客气了，屏幕适配是个很烦的问题，但是你的库能让这个适配变的非常简单呢，能帮你一起完善这个库，我也是很高兴
