### ISSUE TITLE
请问大神，你这个适配已经在项目中开始使用了吗？

### ISSUE THREAD

**Issue by quguangle** [genius158/InflaterAuto#6]
各大手机厂商的兼容性怎么样？有没有已经在项目中使用的APP，并且已经上线了的。性能问题怎么样？
如果这个库比较成熟，我帮你推荐一下。我也想找个比较好的适配。

**Comment by genius158** [comment]
@quguangle 说明一下，为什么会有这个库，最早是因为一个老项目(Android TV项目)，挺大的，布局文件非常多，原本的动态适配方案经常出问题，同时侵入性很强，扩展起来也很麻烦，后来就用了这种偷梁换柱的方法，快速的解决了这个问题(至于兼容性，tv上，在我接近一年的tv开发过程中，是没有出问题的，性能几乎没有影响)。
其实一个项目，从头开始做，或布局不是太多，现在用约束布局结合textview字体大小适应宽高，配合百分比控件，就已经完全够做屏幕适配了。

**Comment by quguangle** [comment]
我们的项目有点大，在上小米市场胡出现适配问题。

**Comment by quguangle** [comment]
之前我也看到你用到了另外一个框架采用PT来适配的，但是机型兼容性有问题。你们textview字体大小也做适配了？

**Comment by genius158** [comment]
另外那个是别人写的，觉得原理还是挺好的，个人只是试试而已，并没有真的用它，非常不稳定。

**Comment by genius158** [comment]
它那种改变系统参数的方法，说起来是很危险的。

**Comment by quguangle** [comment]
嗯！我也测试了，国产手机上有问题

**Comment by quguangle** [comment]
我现在采用的DP来适配，配合相对布局和百分比布局，但是在小米某些机型上还是有问题

**Comment by quguangle** [comment]
图片的加载我都采用的是动态的适配，按照一定的宽高比的比例来适配

**Comment by genius158** [comment]
图片，可以用百分比控件，当然为了减少层级，简单的也可以自己重写一下测量方法。

**Comment by quguangle** [comment]
我们项目中凡是图片都是通过动态计算宽高比来适配的

**Comment by quguangle** [comment]
不然就会出现图片显示不全，或者图片显示不清楚

**Comment by genius158** [comment]
那有什么问题

**Comment by quguangle** [comment]
你们项目中的字体大小也做了适配吗？我想请假一下，你们推送是怎么搞的？

**Comment by quguangle** [comment]
当应用退出之后，在某些手机上根本接收不到

**Comment by quguangle** [comment]
采用双进程拉活，在国产手机上也解决不了问题，你们是怎么解决在手机及时收到推送的

**Comment by quguangle** [comment]
还有一个问题是就是怎么处理应用图标上显示收到推送消息的个数

**Comment by quguangle** [comment]
这个在手机上的兼容性也是很大问题

**Comment by genius158** [comment]
本库是做字体适配的，推送，除了保活，就是用使用率最高的推送(个推，使用的APP挺多的之前了解，至于为什么，可以了解一下推送原理)
图标目前没有怎么涉及

**Comment by quguangle** [comment]
我现在实现的方式去兼容国内厂商自己推出的推送，他们采用的是系统级别的推送，就是很麻烦
