### ISSUE TITLE
错误: 无法从最终InflaterConvert进行继承 public class InfAutoInflaterConvert extends InflaterConvert implements AutoConvert {           

### ISSUE THREAD

**Issue by palorotolo** [genius158/InflaterAuto#8]
![image 13](https://user-images.githubusercontent.com/25273860/38602482-6efbd9e2-3d9d-11e8-8999-83c70b4d268e.png)

**Comment by palorotolo** [comment]
解决 kotlin 的类默认无法被继承……

**Comment by genius158** [comment]
抱歉，目前个人使用到该库的项目均为纯java，kotlin方面的问题，可能就无法处理。

**Comment by palorotolo** [comment]
这个解决了 我的问题 不好意思
